name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.6.0
homepage: https://github.com/mwaylabs/flutter-apns

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: "^3.0.4"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter_apns_only: ^1.6.0
  huawei_push: ^6.10.0+300
  google_api_availability: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
